---
# Sensor button
#    uid:
#    page_id:
#    row:
#    column:
#    row_span:
#    column_span:
#    text:
#    icon:
#    icon_color:
#    bg_color:
#    label_color:
#    value_color:
#    sensor_id:
#    sensor_font:
#    btn_width:
#    btn_height:
#    btn_y_offset:

lvgl:
  pages:
    - id: !extend ${page_id | default("main_page")}
      widgets:
        - container:
            id: ${uid}
            grid_cell_row_pos: ${row}
            grid_cell_column_pos: ${column}
            grid_cell_row_span: ${row_span | default(1)}
            grid_cell_column_span: ${column_span | default(2)}
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            widgets:
              - button:
                  id: button_${sensor_id}
                  bg_color: ${bg_color | default("$button_off_color")}
                  width: ${btn_width | default("100%")}
                  height: ${btn_height | default("100%")}
                  align: CENTER
                  y: ${btn_y_offset | default("0")}
                  layout:
                    type: grid
                    grid_columns: [content, fr(1)]
                    grid_rows: [fr(1), fr(1)]
                  widgets:
                    - label:
                        id: icon_${sensor_id}
                        text_font: $icon_font
                        text_color: ${icon_color | default("$label_on_color")}
                        grid_cell_row_pos: 0
                        grid_cell_column_pos: 0
                        grid_cell_row_span: 2
                        grid_cell_x_align: start
                        grid_cell_y_align: center
                        text: ${icon}
                    - label:
                        id: label_${sensor_id}
                        text_font: nunito_22
                        text_color: ${label_color | default("$label_on_color")}
                        width: 100%
                        long_mode: wrap
                        grid_cell_row_pos: 0
                        grid_cell_column_pos: 1
                        grid_cell_x_align: stretch
                        grid_cell_y_align: start
                        text_align: left
                        text: ${text}
                    - label:
                        id: data_${sensor_id}
                        text_font: ${sensor_font | default("nunito_22")}
                        text_color: ${value_color | default("$label_on_color")}
                        grid_cell_row_pos: 1
                        grid_cell_column_pos: 1
                        grid_cell_x_align: start
                        grid_cell_y_align: end
                        text_align: left
                        text: '----'

sensor:
  - id: !extend ${sensor_id}
    on_value:
      then:
        - lvgl.label.update:
            id: data_${sensor_id}
            text: !lambda |-
              if (isnan(x)) {
                return std::string("--");
              }
              auto unit = id(${sensor_id}).get_unit_of_measurement_ref();
              if (unit.empty()) {
                return str_sprintf("%.1f", x);
              }
              return str_sprintf("%.1f %s", x, unit.c_str());
