# Guition ESP32-S3-4848S040 480px X 480px Smart Screen
#
# Hardware configuration file
---

substitutions:
  # Screen Size
  screen_height: 480
  screen_width: 480

# esphome:
#  min_version: 2026.1.0
#  project:
#    name: "Guition.ESP32-S3-4848S040"
#    version: "1.0"
esphome:
  name: sensecap-d1s
  friendly_name: SenseCAP Indicator
  min_version: 2024.6.0    

#esp32:
#  variant: esp32s3
#  flash_size: 16MB
#  framework:
#    type: esp-idf
#    advanced:
#      execute_from_psram: true

#psram:
#  mode: octal
#  speed: 80MHz

#preferences:
#  flash_write_interval: 5min

# SenseCAP Indicator hardware (ESP32-S3)
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0
  level: DEBUG   # Reduced to improve runtime stability

# api:

# ota:
#  - platform: esphome
#    password: "41def07295f8022fbb33225b9baa335a"

# wifi:
#  ap:
#    ssid: "Fallback AP"
#    password: "1234567890"

# captive_portal:

# web_server:
#  port: 80
#  include_internal: true

safe_mode:
  disabled: false    

# --- I2C BUS --- PCA9554 Expander I2C Address: 0x20, 16bit -and Touchscreen
i2c:
  - id: bus_a
    sda: GPIO39
    scl: GPIO40
    scan: true  #false in docs

# --- SPI BUS ---
spi:
  - id: lcd_spi
    clk_pin: GPIO41
    mosi_pin: GPIO48
    miso_pin: GPIO47

# --- PCA9554 IO EXPANDER --- GPIO39/40
pca9554:
  - id: pca9554a_device
    address: 0x20
    pin_count: 16

# --- RP2040 UART FOR SENSOR PACKET TRANSPORT --- 2nd CPU
uart:
  - id: rp2040_serial
    tx_pin: GPIO20  # TX from ESP32S3 to RP2040 RX RP_16
    rx_pin: GPIO19  # RX to ESP32S3 from RP2040 TX RP_17
    baud_rate: 115200

packet_transport:
  - platform: uart
    uart_id: rp2040_serial
    providers:
      - name: d1-rp2040
# SenseCAP Indicator display + touch + backlight
output:
  - platform: ledc
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: ledc_gpio45
    frequency: 25000Hz  # 100Hz default

light:
  - platform: monochromatic
    id: display_backlight
    output: ledc_gpio45
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    on_turn_on:
      - light.control:
          id: display_backlight
          brightness: 50%  # Default to 50% brightness on power on

# --- DISPLAY (MIPI RGB) ---
display:
  - platform: mipi_rgb
    model: SEEED-INDICATOR-D1
    id: my_display
    invert_colors: true  # Toggle to false
    update_interval: 0s
#    color_order: GRB
    draw_rounding: 2
    auto_clear_enabled: false
    use_axis_flips: true

# --- TOUCHSCREEN (FT5x06) --- I2C 39/40
touchscreen:
  - platform: ft5x06
    id: my_touchscreen
    transform:
      mirror_x: true
      mirror_y: true

# -------------------------------------------
# Internal outputs
# -------------------------------------------
# output:
  # Backlight LED
#  - platform: ledc
#    pin: GPIO38
#    id: gpio_backlight_pwm
#    frequency: 100Hz

  # Built in 240v/120v relay
  # Some versions of this switch have 3 relays some have 1
 # - id: internal_relay_1
 #   platform: gpio
 #   pin: GPIO40
 # - id: internal_relay_2
 #   platform: gpio
 #   pin: GPIO02
 # - id: internal_relay_3
 #   platform: gpio
 #   pin: GPIO01

#light:
#  - platform: monochromatic
#    output: gpio_backlight_pwm
#    name: Display Backlight
#    icon: mdi:lightbulb-on
#    id: display_backlight
#    restore_mode: ALWAYS_ON

# -------------------------------------------
# Touchscreen gt911 i2c
# -------------------------------------------
#i2c:
#  - id: bus_a
#    sda:
#      number: GPIO19
#    scl:
#      number: GPIO45
#      ignore_strapping_warning: true

#touchscreen:
#  platform: gt911
#  id: my_touchscreen
#  display: my_display
#  i2c_id: bus_a
#  transform:
#    mirror_x: false
#   on_touch:
#     - logger.log:
#           format: Touch at (%d, %d)
#           args: [touch.x, touch.y]
#     - lambda: |-
#           ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
#               touch.x,
#               touch.y,
#               touch.x_raw,
#               touch.y_raw
#               );

# -------------------------------------------
# Display st7701s spi
# -------------------------------------------
#spi:
#  - id: lcd_spi
#    clk_pin: GPIO48
#    mosi_pin: GPIO47

#display:
#  - platform: st7701s
#    id: my_display
#    update_interval: never
#    auto_clear_enabled: false
#    spi_mode: MODE3
#    data_rate: 2MHz
#    color_order: RGB
#    invert_colors: false
#    dimensions:
#      width: 480
#      height: 480
#    cs_pin: GPIO39
#    de_pin: GPIO18
#    hsync_pin: GPIO16
#    vsync_pin: GPIO17
#    pclk_pin: GPIO21
#    pclk_frequency: 12MHz
#    pclk_inverted: false
#    hsync_pulse_width: 8
#    hsync_front_porch: 10
#    hsync_back_porch: 20
#    vsync_pulse_width: 8
#    vsync_front_porch: 10
#    vsync_back_porch: 10
#    init_sequence:
#      - 1
#      # Custom sequences are an array, first byte is command, the rest are data.
#      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]  # CMD2_BKSEL_BK0
#      - [0xCD, 0x00]  # disable MDT flag
#    data_pins:
#      red:
#        - 11        # r1
#        - 12        # r2
#        - 13        # r3
#        - 14        # r4
#        - 0         # r5
#      green:
#        - 8         # g0
#        - 20        # g1
#        - 3         # g2
#        - 46        # g3
#        - 9         # g4
#        - 10        # g5
#      blue:
#        - 4         # b1
#        - 5         # b2
#        - 6         # b3
#        - 7         # b4
#        - 15        # b5
