substitutions:
  sense_page_lighting_switches_id: "page_lighting_switches"

lvgl:
  pages:
    - id: ${sense_page_lighting_switches_id}
      styles: sense_page_style
      layout: 5x2
      layout:
        type: grid
        grid_rows:
          - 40
          - FR(1)
          - FR(1)
          - FR(1)
        grid_columns:
          - FR(1)
          - FR(1)
        pad_row: 8
        pad_column: 8
      pad_top: ${sense_content_y | default("46")}
      pad_bottom: 76
      pad_left: 8
      pad_right: 8
      widgets:
        - obj:
            id: light_switches_card_bg
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_row_span: 4
            grid_cell_column_span: 2
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            styles: sense_card_style
            clickable: false
        - label:
            id: light_switches_title
            text: "Lights"
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_column_span: 2
            grid_cell_x_align: center
            grid_cell_y_align: center
            y: -2
            text_font: nunito_36
            text_color: sense_info
