substitutions:
  sense_page_lighting_dimmers_2_id: "page_lighting_dimmers_2"

lvgl:
  pages:
    - id: ${sense_page_lighting_dimmers_2_id}
      styles: sense_page_style
      layout:
        type: grid
        grid_rows:
          - FR(1)
          - FR(1)
          - FR(1)
          - FR(1)
        grid_columns:
          - FR(1)
          - FR(1)
          - FR(1)
          - FR(1)
        pad_row: 8
        pad_column: 8
      pad_top: ${sense_content_y | default("46")}
      pad_bottom: 76
      pad_left: 8
      pad_right: 8
      widgets:
        - obj:
            id: dimmers_page_2_card_bg
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_row_span: 5
            grid_cell_column_span: 4
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            styles: sense_card_style
            clickable: false
        - label:
            id: dimmers_page_2_title
            text: "Dimmers"
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_column_span: 4
            grid_cell_x_align: center
            grid_cell_y_align: center
            y: -2
            text_font: nunito_36
            text_color: sense_info
