substitutions:
  sense_page_lighting_dimmers_id: "page_lighting_dimmers"

lvgl:
  pages:
    - id: ${sense_page_lighting_dimmers_id}
      styles: sense_page_style
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      layout: 5x2
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
      layout:
        type: grid
        grid_rows:
          - FR(1)
          - FR(1)
          - FR(1)
          - FR(1)
        grid_columns:
          - FR(1)
          - FR(1)
          - FR(1)
          - FR(1)
        pad_row: 8
        pad_column: 8
      pad_top: ${sense_content_y | default("46")}
      pad_bottom: 76
      pad_left: 8
      pad_right: 8
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
